### ISSUE TITLE
Upgrade go.mod to go 1.13

### ISSUE THREAD

**Issue by sandokandias** [ZupIT/ritchie-server#6]
### What version of Rit Server are you using?
master

### Does this issue reproduce with the latest release?
yes

### What operating system are you using?
OSX

### What did you do?
make build

### What did you expect to see?
go.mod file -> go 1.13

### What did you see instead?
go.mod file -> go 1.12

**Comment by viniciusramosdefaria** [comment]
@sandokandias, as you can see in the following snippet, this change is already deployed to master:
```
module ritchie-server

go 1.13

require (
```
Closing this issue as it's no longer  valid.
